export default[
    {
        babyName:'Ahmed',
        BabyImage:require('./assets/colin-maynard-CEEhmAGpYzE-unsplash.jpg'),
        BabyAge:'1',
        babyGender:'male',
    },
    {
        babyName:'Fatma',
        BabyImage:require('./assets/christian-bowen-OJOE587CWuE-unsplash.jpg'),
        BabyAge:'1',
        babyGender:'female',
    },
    {
        babyName:'Sammy',
        BabyImage:require('./assets/homeimages/lucas-margoni-nWbJlwIrmT8-unsplash.jpg'),
        BabyAge:'1',
        babyGender:'male',
    },
    {
        babyName:'Sara',
        BabyImage:require('./assets/homeimages/jonathan-borba-oHB7VKdpHQM-unsplash.jpg'),
        BabyAge:'1',
        babyGender:'male',
    },
    {
        babyName:'Sara',
        BabyImage:require('./assets/homeimages/jonathan-borba-oHB7VKdpHQM-unsplash.jpg'),
        BabyAge:'1',
        babyGender:'male',
    },{
        babyName:'Sara',
        BabyImage:require('./assets/homeimages/jonathan-borba-oHB7VKdpHQM-unsplash.jpg'),
        BabyAge:'1',
        babyGender:'male',
    },

    
]