export default[
    {
        image:require('./assets/homeimages/OIP.jpeg'),
        nameOfProduct:'product1',
        rate:'2'
    },
    {
        image:require('./assets/homeimages/baby_clothes.jpg'),
        nameOfProduct:'product2',
        rate:'3'
    },
    {
        image:require('./assets/homeimages/feeding_baby.jpg'),
        nameOfProduct:'product3',
        rate:'4'
    },
    {
        image:require('./assets/homeimages/R.jpeg'),
        nameOfProduct:'product4',
        rate:'5'
    }
]